name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Build all platforms
        run: make release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.zip
            build/*.spk
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true 